package com.vuatho.testcases;

/** Danh mục testcase cố định của màn hình Lịch sử giao dịch. */
public final class TransactionHistoryTestCases {
    public static final String TRANSACTION_ALL_001 = "TRANSACTION-ALL-001 - Mở đúng tab Tất cả";
    public static final String TRANSACTION_ALL_002 = "TRANSACTION-ALL-002 - Hiển thị đầy đủ các nhóm giao dịch";
    public static final String TRANSACTION_ALL_003 = "TRANSACTION-ALL-003 - Hiển thị đầy đủ bộ lọc và xuất Excel";
    public static final String TRANSACTION_ALL_004 = "TRANSACTION-ALL-004 - Bảng Tất cả hiển thị đúng các cột";
    public static final String TRANSACTION_ALL_005 = "TRANSACTION-ALL-005 - Dòng giao dịch có định dạng hợp lệ";
    public static final String TRANSACTION_ALL_006 = "TRANSACTION-ALL-006 - Mỗi trang hiển thị tối đa hai mươi giao dịch";
    public static final String TRANSACTION_ALL_007 = "TRANSACTION-ALL-007 - Hiển thị tổng số giao dịch và phân trang";
    public static final String TRANSACTION_ALL_008 = "TRANSACTION-ALL-008 - Bộ lọc loại giao dịch có đầy đủ lựa chọn";
    public static final String TRANSACTION_ALL_009 = "TRANSACTION-ALL-009 - Bộ lọc trạng thái có đầy đủ lựa chọn";
    public static final String TRANSACTION_ALL_010 = "TRANSACTION-ALL-010 - Bộ lọc cổng thanh toán có đầy đủ lựa chọn";
    public static final String TRANSACTION_ALL_011 = "TRANSACTION-ALL-011 - Lọc theo loại giao dịch lấy từ dữ liệu thật";
    public static final String TRANSACTION_ALL_012 = "TRANSACTION-ALL-012 - Lọc theo trạng thái lấy từ dữ liệu thật";
    public static final String TRANSACTION_ALL_013 = "TRANSACTION-ALL-013 - Lọc theo cổng thanh toán lấy từ dữ liệu thật";
    public static final String TRANSACTION_ALL_014 = "TRANSACTION-ALL-014 - Kết hợp nhiều bộ lọc trả đúng giao dịch";
    public static final String TRANSACTION_ALL_015 = "TRANSACTION-ALL-015 - Không cho chọn ngày giao dịch tương lai";
    public static final String TRANSACTION_ALL_016 = "TRANSACTION-ALL-016 - Lọc khoảng ngày bao gồm hai đầu mút";
    public static final String TRANSACTION_ALL_017 = "TRANSACTION-ALL-017 - Tổ hợp không khớp hiển thị trạng thái chưa có dữ liệu";
    public static final String TRANSACTION_ALL_018 = "TRANSACTION-ALL-018 - Reset xóa bộ lọc nhưng giữ tab Tất cả";
    public static final String TRANSACTION_ALL_019 = "TRANSACTION-ALL-019 - Reset trạng thái rỗng khôi phục dữ liệu";
    public static final String TRANSACTION_ALL_020 = "TRANSACTION-ALL-020 - Sắp xếp số tiền tăng dần";
    public static final String TRANSACTION_ALL_021 = "TRANSACTION-ALL-021 - Sắp xếp số tiền giảm dần";
    public static final String TRANSACTION_ALL_022 = "TRANSACTION-ALL-022 - Sắp xếp ngày tạo tăng và giảm dần";
    public static final String TRANSACTION_ALL_023 = "TRANSACTION-ALL-023 - Cột không hỗ trợ sắp xếp không đổi dữ liệu";
    public static final String TRANSACTION_ALL_024 = "TRANSACTION-ALL-024 - Chuyển trang làm thay đổi tập dữ liệu";
    public static final String TRANSACTION_ALL_025 = "TRANSACTION-ALL-025 - Quay lại trang một khôi phục tập dữ liệu";
    public static final String TRANSACTION_ALL_026 = "TRANSACTION-ALL-026 - Bộ lọc được giữ nguyên khi chuyển trang";
    public static final String TRANSACTION_ALL_027 = "TRANSACTION-ALL-027 - Reset từ trang sau quay về trang một";
    public static final String TRANSACTION_ALL_028 = "TRANSACTION-ALL-028 - Mở chi tiết từ một dòng giao dịch";
    public static final String TRANSACTION_ALL_029 = "TRANSACTION-ALL-029 - Chi tiết hiển thị đủ thông tin giao dịch";
    public static final String TRANSACTION_ALL_030 = "TRANSACTION-ALL-030 - Chi tiết hiển thị tổng dòng tiền";
    public static final String TRANSACTION_ALL_031 = "TRANSACTION-ALL-031 - Giao dịch đang xem được đánh dấu trong lịch sử liên quan";
    public static final String TRANSACTION_ALL_032 = "TRANSACTION-ALL-032 - Đóng chi tiết xóa mã giao dịch khỏi URL";
    public static final String TRANSACTION_ALL_033 = "TRANSACTION-ALL-033 - Deep link mở lại đúng chi tiết giao dịch";
    public static final String TRANSACTION_ALL_034 = "TRANSACTION-ALL-034 - Xuất Excel toàn bộ tab Tất cả";
    public static final String TRANSACTION_ALL_035 = "TRANSACTION-ALL-035 - File Excel có tiêu đề và dữ liệu giao dịch";
    public static final String TRANSACTION_ALL_036 = "TRANSACTION-ALL-036 - Excel xuất toàn bộ dữ liệu phù hợp bộ lọc";
    public static final String TRANSACTION_ALL_037 = "TRANSACTION-ALL-037 - Chi tiết khớp loại giao dịch của dòng được chọn";
    public static final String TRANSACTION_ALL_038 = "TRANSACTION-ALL-038 - Chi tiết khớp trạng thái của dòng được chọn";
    public static final String TRANSACTION_ALL_039 = "TRANSACTION-ALL-039 - Chi tiết khớp số tiền của dòng được chọn";
    public static final String TRANSACTION_ALL_040 = "TRANSACTION-ALL-040 - Chi tiết khớp cổng thanh toán và thời gian";
    public static final String TRANSACTION_ALL_041 = "TRANSACTION-ALL-041 - URL chi tiết chứa đúng một mã giao dịch";
    public static final String TRANSACTION_ALL_042 = "TRANSACTION-ALL-042 - Tải lại trang giữ nguyên chi tiết đang mở";
    public static final String TRANSACTION_ALL_043 = "TRANSACTION-ALL-043 - Back và Forward đóng mở lại đúng chi tiết";
    public static final String TRANSACTION_ALL_044 = "TRANSACTION-ALL-044 - Lịch sử dòng tiền tải xong không còn trạng thái chờ";
    public static final String TRANSACTION_ALL_045 = "TRANSACTION-ALL-045 - Giao dịch hiện tại trong dòng tiền khớp dữ liệu nguồn";
    public static final String TRANSACTION_ALL_046 = "TRANSACTION-ALL-046 - Mở giao dịch khác cập nhật mã và nội dung chi tiết";
    public static final String TRANSACTION_ALL_047 = "TRANSACTION-ALL-047 - Đổi trạng thái cập nhật bộ lọc và dữ liệu";
    public static final String TRANSACTION_ALL_048 = "TRANSACTION-ALL-048 - Lần lượt lọc được theo mọi trạng thái";
    public static final String TRANSACTION_ALL_049 = "TRANSACTION-ALL-049 - Lần lượt lọc được theo mọi cổng thanh toán";
    public static final String TRANSACTION_ALL_050 = "TRANSACTION-ALL-050 - Đóng bộ lọc không chọn giữ nguyên dữ liệu";
    public static final String TRANSACTION_ALL_051 = "TRANSACTION-ALL-051 - Bộ chọn ngày có giờ mặc định cả ngày";
    public static final String TRANSACTION_ALL_052 = "TRANSACTION-ALL-052 - Chưa chọn ngày không cho áp dụng bộ lọc";
    public static final String TRANSACTION_ALL_053 = "TRANSACTION-ALL-053 - Lọc giao dịch trong cùng một ngày";
    public static final String TRANSACTION_ALL_054 = "TRANSACTION-ALL-054 - Lọc theo khoảng giờ trong ngày";
    public static final String TRANSACTION_ALL_055 = "TRANSACTION-ALL-055 - Đóng bộ chọn ngày chưa áp dụng giữ nguyên dữ liệu";
    public static final String TRANSACTION_ALL_056 = "TRANSACTION-ALL-056 - Kết hợp ngày loại trạng thái và cổng thanh toán";
    public static final String TRANSACTION_ALL_057 = "TRANSACTION-ALL-057 - Tổng số và phân trang cập nhật theo bộ lọc";
    public static final String TRANSACTION_ALL_058 = "TRANSACTION-ALL-058 - Bộ lọc được giữ khi mở và đóng chi tiết";
    public static final String TRANSACTION_ALL_059 = "TRANSACTION-ALL-059 - Reset xóa toàn bộ bộ lọc kết hợp và ngày";
    public static final String TRANSACTION_ALL_060 = "TRANSACTION-ALL-060 - Xóa riêng khoảng ngày khôi phục toàn bộ dữ liệu";
    public static final String TRANSACTION_ALL_061 = "TRANSACTION-ALL-061 - Bộ lọc không thuộc tab Tất cả được giữ ẩn";
    public static final String TRANSACTION_ALL_062 = "TRANSACTION-ALL-062 - Previous bị khóa tại trang đầu";
    public static final String TRANSACTION_ALL_063 = "TRANSACTION-ALL-063 - Next chuyển đúng sang trang kế tiếp";
    public static final String TRANSACTION_ALL_064 = "TRANSACTION-ALL-064 - Previous quay đúng về trang trước";
    public static final String TRANSACTION_ALL_065 = "TRANSACTION-ALL-065 - Trang hiện tại được đánh dấu active";
    public static final String TRANSACTION_ALL_066 = "TRANSACTION-ALL-066 - Đi được đến trang cuối và Next bị khóa";
    public static final String TRANSACTION_ALL_067 = "TRANSACTION-ALL-067 - Trang cuối không vượt quá giới hạn số dòng";
    public static final String TRANSACTION_ALL_068 = "TRANSACTION-ALL-068 - Hai trang liên tiếp không trùng giao dịch";
    public static final String TRANSACTION_ALL_069 = "TRANSACTION-ALL-069 - Thứ tự số tiền được giữ khi chuyển trang";
    public static final String TRANSACTION_ALL_070 = "TRANSACTION-ALL-070 - Quay lại trang đầu giữ nguyên chiều sắp xếp";
    public static final String TRANSACTION_ALL_071 = "TRANSACTION-ALL-071 - Đổi bộ lọc từ trang sau quay về trang đầu";
    public static final String TRANSACTION_ALL_072 = "TRANSACTION-ALL-072 - Đóng chi tiết từ trang sau giữ nguyên trang";
    public static final String TRANSACTION_ALL_073 = "TRANSACTION-ALL-073 - Reset sau sắp xếp khôi phục thứ tự mặc định";
    public static final String TRANSACTION_ALL_074 = "TRANSACTION-ALL-074 - Nút dấu ba chấm nhảy đến nhóm trang sau";

    public static final String TRANSACTION_DEPOSIT_001 = "TRANSACTION-DEPOSIT-001 - Tiền nạp: Hiển thị đầy đủ các loại giao dịch con";
    public static final String TRANSACTION_DEPOSIT_002 = "TRANSACTION-DEPOSIT-002 - Tiền nạp: Mở đúng route và đánh dấu loại đang chọn";
    public static final String TRANSACTION_DEPOSIT_003 = "TRANSACTION-DEPOSIT-003 - Tiền nạp: Hiển thị đúng bộ lọc và cột dữ liệu";
    public static final String TRANSACTION_DEPOSIT_004 = "TRANSACTION-DEPOSIT-004 - Tiền nạp: Dòng giao dịch có định dạng hợp lệ";
    public static final String TRANSACTION_DEPOSIT_005 = "TRANSACTION-DEPOSIT-005 - Tiền nạp: Với từng loại có người dùng, nhập tên hoặc SĐT của dòng đầu chỉ hiển thị giao dịch chứa từ khóa, xóa từ khóa khôi phục danh sách";
    public static final String TRANSACTION_DEPOSIT_006 = "TRANSACTION-DEPOSIT-006 - Tiền nạp: Mở bộ lọc trạng thái rồi Reset không làm đổi URL và loại Tiền nạp đang xem";
    public static final String TRANSACTION_DEPOSIT_007 = "TRANSACTION-DEPOSIT-007 - Tiền nạp: Sắp xếp số tiền tăng và giảm dần";
    public static final String TRANSACTION_DEPOSIT_008 = "TRANSACTION-DEPOSIT-008 - Tiền nạp: Mở và đóng chi tiết giao dịch";
    public static final String TRANSACTION_DEPOSIT_009 = "TRANSACTION-DEPOSIT-009 - Tiền nạp: Phân trang và Reset giữ đúng tab";
    public static final String TRANSACTION_DEPOSIT_010 = "TRANSACTION-DEPOSIT-010 - Tiền nạp: Xuất Excel cho loại giao dịch đang chọn";
    public static final String TRANSACTION_DEPOSIT_011 = "TRANSACTION-DEPOSIT-011 - Tiền nạp: Trigger mở đúng menu được liên kết";
    public static final String TRANSACTION_DEPOSIT_012 = "TRANSACTION-DEPOSIT-012 - Tiền nạp: Option có đúng key và trạng thái lựa chọn";
    public static final String TRANSACTION_DEPOSIT_013 = "TRANSACTION-DEPOSIT-013 - Tiền nạp: Đổi loại cập nhật đúng dữ liệu giao dịch";
    public static final String TRANSACTION_DEPOSIT_014 = "TRANSACTION-DEPOSIT-014 - Tiền nạp: Chọn loại cập nhật duy nhất trạng thái đang chọn";
    public static final String TRANSACTION_DEPOSIT_015 = "TRANSACTION-DEPOSIT-015 - Tiền nạp: Đóng dropdown bằng trigger giữ nguyên loại đang chọn";
    public static final String TRANSACTION_DEPOSIT_016 = "TRANSACTION-DEPOSIT-016 - Tiền nạp: Đóng dropdown bằng Escape giữ nguyên loại đang chọn";
    public static final String TRANSACTION_DEPOSIT_017 = "TRANSACTION-DEPOSIT-017 - Tiền nạp: Chi tiết khớp dòng đã chọn và hiển thị đủ thông tin nạp";
    public static final String TRANSACTION_DEPOSIT_018 = "TRANSACTION-DEPOSIT-018 - Tiền nạp: Lịch sử dòng tiền tải xong và đánh dấu giao dịch hiện tại";
    public static final String TRANSACTION_DEPOSIT_019 = "TRANSACTION-DEPOSIT-019 - Tiền nạp: Liên kết người nạp và giao dịch liên quan hợp lệ";
    public static final String TRANSACTION_DEPOSIT_020 = "TRANSACTION-DEPOSIT-020 - Tiền nạp: Deep link mở lại đúng chi tiết giao dịch";
    public static final String TRANSACTION_DEPOSIT_021 = "TRANSACTION-DEPOSIT-021 - Tiền nạp: Back và Forward đóng rồi khôi phục chi tiết";
    public static final String TRANSACTION_DEPOSIT_022 = "TRANSACTION-DEPOSIT-022 - Tiền nạp: Xem thêm tải thêm lịch sử dòng tiền";
    public static final String TRANSACTION_DEPOSIT_023 = "TRANSACTION-DEPOSIT-023 - Tiền nạp: Giao dịch liên quan mở đúng chi tiết đích";
    public static final String TRANSACTION_DEPOSIT_024 = "TRANSACTION-DEPOSIT-024 - Tiền nạp: Chi tiết Bên thứ 3 hiển thị đúng thông tin hai bên";
    public static final String TRANSACTION_DEPOSIT_025 = "TRANSACTION-DEPOSIT-025 - Tiền nạp: Chi tiết Nạp từ DN hiển thị đúng số dư Ví";
    public static final String TRANSACTION_DEPOSIT_026 = "TRANSACTION-DEPOSIT-026 - Tiền nạp: Chi tiết Nạp ký quỹ qua NH hiển thị đúng người nhận";
    public static final String TRANSACTION_DEPOSIT_027 = "TRANSACTION-DEPOSIT-027 - Tiền nạp: Chi tiết Nạp vào ký quỹ hiển thị đúng biến động số dư";
    public static final String TRANSACTION_DEPOSIT_028 = "TRANSACTION-DEPOSIT-028 - Tiền nạp: Mỗi loại mở đúng chi tiết theo ba trạng thái";
    public static final String TRANSACTION_DEPOSIT_029 = "TRANSACTION-DEPOSIT-029 - Tiền nạp: Icon đóng giữ nguyên loại giao dịch";
    public static final String TRANSACTION_DEPOSIT_030 = "TRANSACTION-DEPOSIT-030 - Tiền nạp: Escape đóng chi tiết và giữ nguyên loại giao dịch";
    public static final String TRANSACTION_DEPOSIT_031 = "TRANSACTION-DEPOSIT-031 - Tiền nạp: Liên kết chủ thể mở đúng hồ sơ";
    public static final String TRANSACTION_DEPOSIT_032 = "TRANSACTION-DEPOSIT-032 - Tiền nạp: Refresh giữ nguyên chi tiết đang mở";
    public static final String TRANSACTION_DEPOSIT_033 = "TRANSACTION-DEPOSIT-033 - Tiền nạp: Trên từng loại, lần lượt chọn Đang chờ, Thành công và Đã hủy chỉ hiển thị dòng đúng trạng thái đã chọn";
    public static final String TRANSACTION_DEPOSIT_034 = "TRANSACTION-DEPOSIT-034 - Tiền nạp: Trên từng loại, lần lượt chọn MOMO, PAYPAL, ONEPAY, BANKING và NEOX chỉ hiển thị dòng đúng cổng đã chọn";
    public static final String TRANSACTION_DEPOSIT_035 = "TRANSACTION-DEPOSIT-035 - Tiền nạp: Trên Nạp thường, kết hợp từng trạng thái Đang chờ, Thành công, Đã hủy với từng cổng MOMO, PAYPAL, ONEPAY, BANKING, NEOX cho kết quả khớp hoặc rỗng";
    public static final String TRANSACTION_DEPOSIT_036 = "TRANSACTION-DEPOSIT-036 - Tiền nạp: Mở bộ lọc Trạng thái rồi Escape, mở bộ lọc Cổng thanh toán rồi Escape vẫn giữ giá trị và danh sách ban đầu";
    public static final String TRANSACTION_DEPOSIT_037 = "TRANSACTION-DEPOSIT-037 - Tiền nạp: Mở bộ lọc ngày và kiểm tra ngày mai cùng các ngày tương lai đều bị vô hiệu hóa";
    public static final String TRANSACTION_DEPOSIT_038 = "TRANSACTION-DEPOSIT-038 - Tiền nạp: Mở bộ lọc ngày hiển thị giờ bắt đầu 00:00, giờ kết thúc 23:59 và khóa nút Áp dụng khi chưa chọn ngày";
    public static final String TRANSACTION_DEPOSIT_039 = "TRANSACTION-DEPOSIT-039 - Tiền nạp: Chọn ngày tạo của dòng đầu từ 00:00 đến 23:59 chỉ hiển thị giao dịch trong đúng ngày đó";
    public static final String TRANSACTION_DEPOSIT_040 = "TRANSACTION-DEPOSIT-040 - Tiền nạp: Chọn khoảng từ phút tạo dòng đầu đến một phút sau chỉ hiển thị giao dịch nằm trong khoảng";
    public static final String TRANSACTION_DEPOSIT_041 = "TRANSACTION-DEPOSIT-041 - Tiền nạp: Chọn ngày tạo của dòng đầu rồi Escape không bấm Áp dụng vẫn giữ ngày và danh sách ban đầu";
    public static final String TRANSACTION_DEPOSIT_042 = "TRANSACTION-DEPOSIT-042 - Tiền nạp: Nhập NO_DEPOSIT_TRANSACTION_987654321 hiển thị Chưa có dữ liệu, Reset khôi phục danh sách và đúng loại";
    public static final String TRANSACTION_DEPOSIT_043 = "TRANSACTION-DEPOSIT-043 - Tiền nạp: Chọn trạng thái Thành công giảm hoặc giữ nguyên tổng, cập nhật phân trang và chỉ hiển thị dòng Thành công";
    public static final String TRANSACTION_DEPOSIT_044 = "TRANSACTION-DEPOSIT-044 - Tiền nạp: Chọn Thành công, mở chi tiết dòng đầu rồi bấm Hủy vẫn giữ bộ lọc, danh sách và type của loại đang xem trên URL";
    public static final String TRANSACTION_DEPOSIT_045 = "TRANSACTION-DEPOSIT-045 - Tiền nạp: Chọn ngày tạo của dòng đầu, sau đó bấm Xóa khoảng ngày để khôi phục tổng dữ liệu ban đầu";
    public static final String TRANSACTION_DEPOSIT_046 = "TRANSACTION-DEPOSIT-046 - Tiền nạp: Chọn ngày của dòng đầu, trạng thái Thành công và cổng MOMO cho kết quả khớp cả ba hoặc trạng thái rỗng";
    public static final String TRANSACTION_DEPOSIT_047 = "TRANSACTION-DEPOSIT-047 - Tiền nạp: Sau khi lọc ngày của dòng đầu, trạng thái Thành công và cổng MOMO, Reset xóa cả ba và giữ đúng loại";
    public static final String TRANSACTION_DEPOSIT_048 = "TRANSACTION-DEPOSIT-048 - Tiền nạp: Chỉ hiển thị Tên/SĐT, Trạng thái, Cổng thanh toán và Ngày giờ; ẩn Loại giao dịch, Xuất hóa đơn và Thời hạn BH";
    public static final String TRANSACTION_DEPOSIT_049 = "TRANSACTION-DEPOSIT-049 - Tiền nạp: Trên Nạp thường, sắp xếp Ngày tạo tăng dần rồi giảm dần cho thứ tự thời gian chính xác và vẫn giữ type=0";
    public static final String TRANSACTION_DEPOSIT_050 = "TRANSACTION-DEPOSIT-050 - Tiền nạp: Trên Nạp thường, click Loại giao dịch, Trạng thái và Cổng thanh toán không làm thay đổi thứ tự vì ba cột không hỗ trợ sort";
    public static final String TRANSACTION_DEPOSIT_051 = "TRANSACTION-DEPOSIT-051 - Tiền nạp: Trên Nạp thường, trang 2 có dữ liệu khác trang 1 và quay lại trang 1 khôi phục đúng danh sách ban đầu";
    public static final String TRANSACTION_DEPOSIT_052 = "TRANSACTION-DEPOSIT-052 - Tiền nạp: Trên Nạp thường, lọc Thành công rồi sang trang 2 vẫn giữ bộ lọc và chỉ hiển thị giao dịch Thành công";
    public static final String TRANSACTION_DEPOSIT_053 = "TRANSACTION-DEPOSIT-053 - Tiền nạp: Trên trang 1 của Nạp thường, nút Trước bị khóa và nút Sau khả dụng";
    public static final String TRANSACTION_DEPOSIT_054 = "TRANSACTION-DEPOSIT-054 - Tiền nạp: Trên Nạp thường, nút Sau mở trang 2 có active marker đúng và nút Trước đưa về trang 1";
    public static final String TRANSACTION_DEPOSIT_055 = "TRANSACTION-DEPOSIT-055 - Tiền nạp: Trên Nạp thường, trang cuối khóa nút Sau và hiển thị từ 1 đến 20 giao dịch";
    public static final String TRANSACTION_DEPOSIT_056 = "TRANSACTION-DEPOSIT-056 - Tiền nạp: Trên Nạp thường, trang 1 và trang 2 không chứa giao dịch trùng nhau";
    public static final String TRANSACTION_DEPOSIT_057 = "TRANSACTION-DEPOSIT-057 - Tiền nạp: Trên Nạp thường, sort Số tiền giảm dần được giữ ở trang 2 và khi quay lại trang 1";
    public static final String TRANSACTION_DEPOSIT_058 = "TRANSACTION-DEPOSIT-058 - Tiền nạp: Trên Nạp thường, chọn trạng thái của dòng đầu khi đang ở trang 2 tự quay về trang 1 và chỉ hiển thị trạng thái đã chọn";
    public static final String TRANSACTION_DEPOSIT_059 = "TRANSACTION-DEPOSIT-059 - Tiền nạp: Trên trang 2 của Nạp thường, mở rồi bấm Hủy chi tiết vẫn giữ trang 2, danh sách và type=0";
    public static final String TRANSACTION_DEPOSIT_060 = "TRANSACTION-DEPOSIT-060 - Tiền nạp: Trên Nạp thường, Reset sau khi sort Số tiền giảm dần khôi phục thứ tự mặc định và trang 1";
    public static final String TRANSACTION_DEPOSIT_061 = "TRANSACTION-DEPOSIT-061 - Tiền nạp: Trên Nạp thường, nút dấu ba chấm chuyển sang nhóm trang sau và tải dữ liệu tương ứng";
    public static final String TRANSACTION_DEPOSIT_062 = "TRANSACTION-DEPOSIT-062 - Tiền nạp: Mỗi loại chỉ hiển thị dòng có đúng loại giao dịch tương ứng";
    public static final String TRANSACTION_DEPOSIT_063 = "TRANSACTION-DEPOSIT-063 - Tiền nạp: Trạng thái và cổng thanh toán của từng dòng thuộc tập giá trị hợp lệ của loại đang xem";
    public static final String TRANSACTION_DEPOSIT_064 = "TRANSACTION-DEPOSIT-064 - Tiền nạp: Nạp thường, Bên thứ 3, Nạp từ DN và Nạp vào ký quỹ hiển thị thống kê Ví chi phí; Nạp ký quỹ qua NH hiển thị thống kê chuyển khoản";
    public static final String TRANSACTION_DEPOSIT_065 = "TRANSACTION-DEPOSIT-065 - Tiền nạp: Sau Reset không lọc trạng thái hoặc cổng; tổng tiền bằng tổng toàn bộ cổng được biểu đồ hiển thị và tổng tỷ lệ xấp xỉ 100%";
    public static final String TRANSACTION_DEPOSIT_066 = "TRANSACTION-DEPOSIT-066 - Tiền nạp: Trên Nạp ký quỹ qua NH, thống kê Hoàn thành, Đang chờ và Từ chối có số tiền, số giao dịch và tổng tỷ lệ hợp lệ";
    public static final String TRANSACTION_DEPOSIT_067 = "TRANSACTION-DEPOSIT-067 - Tiền nạp: Mỗi loại tải xong trạng thái ban đầu, hiển thị tối đa 20 dòng hoặc trạng thái rỗng hợp lệ";

    public static final String TRANSACTION_WITHDRAW_001 = "TRANSACTION-WITHDRAW-001 - Tiền rút: Hiển thị đầy đủ các loại giao dịch con";
    public static final String TRANSACTION_WITHDRAW_002 = "TRANSACTION-WITHDRAW-002 - Tiền rút: Mở đúng route và đánh dấu loại đang chọn";
    public static final String TRANSACTION_WITHDRAW_003 = "TRANSACTION-WITHDRAW-003 - Tiền rút: Hiển thị đúng bộ lọc và cột dữ liệu";
    public static final String TRANSACTION_WITHDRAW_004 = "TRANSACTION-WITHDRAW-004 - Tiền rút: Dòng giao dịch có định dạng hợp lệ";
    public static final String TRANSACTION_WITHDRAW_005 = "TRANSACTION-WITHDRAW-005 - Tiền rút: Tìm kiếm người dùng và Reset khôi phục dữ liệu";
    public static final String TRANSACTION_WITHDRAW_006 = "TRANSACTION-WITHDRAW-006 - Tiền rút: Bộ lọc hiển thị lựa chọn và giữ đúng tab";
    public static final String TRANSACTION_WITHDRAW_007 = "TRANSACTION-WITHDRAW-007 - Tiền rút: Sắp xếp số tiền tăng và giảm dần";
    public static final String TRANSACTION_WITHDRAW_008 = "TRANSACTION-WITHDRAW-008 - Tiền rút: Mở và đóng chi tiết giao dịch";
    public static final String TRANSACTION_WITHDRAW_009 = "TRANSACTION-WITHDRAW-009 - Tiền rút: Phân trang và Reset giữ đúng tab";
    public static final String TRANSACTION_WITHDRAW_010 = "TRANSACTION-WITHDRAW-010 - Tiền rút: Xuất Excel cho loại giao dịch đang chọn";

    public static final String TRANSACTION_ORDER_001 = "TRANSACTION-ORDER-001 - Đơn dịch vụ: Hiển thị đầy đủ các loại giao dịch con";
    public static final String TRANSACTION_ORDER_002 = "TRANSACTION-ORDER-002 - Đơn dịch vụ: Mở đúng route và đánh dấu loại đang chọn";
    public static final String TRANSACTION_ORDER_003 = "TRANSACTION-ORDER-003 - Đơn dịch vụ: Hiển thị đúng bộ lọc và cột dữ liệu";
    public static final String TRANSACTION_ORDER_004 = "TRANSACTION-ORDER-004 - Đơn dịch vụ: Dòng giao dịch có định dạng hợp lệ";
    public static final String TRANSACTION_ORDER_005 = "TRANSACTION-ORDER-005 - Đơn dịch vụ: Tìm kiếm người dùng và Reset khôi phục dữ liệu";
    public static final String TRANSACTION_ORDER_006 = "TRANSACTION-ORDER-006 - Đơn dịch vụ: Bộ lọc hiển thị lựa chọn và giữ đúng tab";
    public static final String TRANSACTION_ORDER_007 = "TRANSACTION-ORDER-007 - Đơn dịch vụ: Sắp xếp số tiền tăng và giảm dần";
    public static final String TRANSACTION_ORDER_008 = "TRANSACTION-ORDER-008 - Đơn dịch vụ: Mở và đóng chi tiết giao dịch";
    public static final String TRANSACTION_ORDER_009 = "TRANSACTION-ORDER-009 - Đơn dịch vụ: Phân trang và Reset giữ đúng tab";
    public static final String TRANSACTION_ORDER_010 = "TRANSACTION-ORDER-010 - Đơn dịch vụ: Xuất Excel cho loại giao dịch đang chọn";

    public static final String TRANSACTION_REWARD_001 = "TRANSACTION-REWARD-001 - Thưởng và khuyến mãi: Hiển thị đầy đủ các loại giao dịch con";
    public static final String TRANSACTION_REWARD_002 = "TRANSACTION-REWARD-002 - Thưởng và khuyến mãi: Mở đúng route và đánh dấu loại đang chọn";
    public static final String TRANSACTION_REWARD_003 = "TRANSACTION-REWARD-003 - Thưởng và khuyến mãi: Hiển thị đúng bộ lọc và cột dữ liệu";
    public static final String TRANSACTION_REWARD_004 = "TRANSACTION-REWARD-004 - Thưởng và khuyến mãi: Dòng giao dịch có định dạng hợp lệ";
    public static final String TRANSACTION_REWARD_005 = "TRANSACTION-REWARD-005 - Thưởng và khuyến mãi: Tìm kiếm người dùng và Reset khôi phục dữ liệu";
    public static final String TRANSACTION_REWARD_006 = "TRANSACTION-REWARD-006 - Thưởng và khuyến mãi: Bộ lọc hiển thị lựa chọn và giữ đúng tab";
    public static final String TRANSACTION_REWARD_007 = "TRANSACTION-REWARD-007 - Thưởng và khuyến mãi: Sắp xếp số tiền tăng và giảm dần";
    public static final String TRANSACTION_REWARD_008 = "TRANSACTION-REWARD-008 - Thưởng và khuyến mãi: Mở và đóng chi tiết giao dịch";
    public static final String TRANSACTION_REWARD_009 = "TRANSACTION-REWARD-009 - Thưởng và khuyến mãi: Phân trang và Reset giữ đúng tab";
    public static final String TRANSACTION_REWARD_010 = "TRANSACTION-REWARD-010 - Thưởng và khuyến mãi: Xuất Excel cho loại giao dịch đang chọn";

    public static final String TRANSACTION_FEE_001 = "TRANSACTION-FEE-001 - Phí và doanh thu: Dropdown hiển thị Phí kết nối, Phí liên kết ví và Phí chia sẻ vật tư";
    public static final String TRANSACTION_FEE_002 = "TRANSACTION-FEE-002 - Phí và doanh thu: Chọn từng loại mở đúng tab=fee, type=8/9/33 và hiển thị đúng loại";
    public static final String TRANSACTION_FEE_003 = "TRANSACTION-FEE-003 - Phí và doanh thu: Type 8 có năm cột; type 9/33 thêm Cổng thanh toán; mọi loại đủ Tên/SĐT, Hoá đơn, Ngày giờ và Excel";
    public static final String TRANSACTION_FEE_004 = "TRANSACTION-FEE-004 - Phí và doanh thu: Mỗi loại có người dùng, trạng thái, tiền và ngày tạo đúng định dạng";
    public static final String TRANSACTION_FEE_005 = "TRANSACTION-FEE-005 - Phí và doanh thu: Tìm tên/SĐT thật trên từng loại rồi xoá từ khoá khôi phục đúng danh sách";
    public static final String TRANSACTION_FEE_006 = "TRANSACTION-FEE-006 - Phí và doanh thu: Mở bộ lọc Xuất hoá đơn rồi Reset vẫn giữ đúng type=8/9/33";
    public static final String TRANSACTION_FEE_007 = "TRANSACTION-FEE-007 - Phí và doanh thu: Số tiền trên từng loại sắp xếp đúng tăng dần rồi giảm dần";
    public static final String TRANSACTION_FEE_008 = "TRANSACTION-FEE-008 - Phí và doanh thu: Mỗi type=8/9/33 mở chi tiết, có thông tin giao dịch và đóng về đúng loại";
    public static final String TRANSACTION_FEE_009 = "TRANSACTION-FEE-009 - Phí và doanh thu: Next chuyển trang, Reset về trang 1 và giữ đúng type=8/9/33";
    public static final String TRANSACTION_FEE_010 = "TRANSACTION-FEE-010 - Phí và doanh thu: Xuất tệp Excel thật cho từng type=8/9/33";
    public static final String TRANSACTION_FEE_011 = "TRANSACTION-FEE-011 - Phí và doanh thu: Dropdown liên kết đúng menu và các key 8, 9, 33 chỉ có một lựa chọn được đánh dấu";
    public static final String TRANSACTION_FEE_012 = "TRANSACTION-FEE-012 - Phí và doanh thu: Chọn từng loại đánh dấu đúng option duy nhất rồi tự đóng dropdown";
    public static final String TRANSACTION_FEE_013 = "TRANSACTION-FEE-013 - Phí và doanh thu: Bấm lại trigger đóng dropdown và giữ Phí kết nối type=8";
    public static final String TRANSACTION_FEE_014 = "TRANSACTION-FEE-014 - Phí và doanh thu: Nhấn Escape đóng dropdown và giữ Phí kết nối type=8";
    public static final String TRANSACTION_FEE_015 = "TRANSACTION-FEE-015 - Phí và doanh thu: Dòng của type=8/9/33 chỉ hiển thị đúng loại Phí kết nối/Liên kết ví/Chia sẻ vật tư";
    public static final String TRANSACTION_FEE_016 = "TRANSACTION-FEE-016 - Phí và doanh thu: Type 8 hiện Tổng doanh thu; type 9 hiện Tổng phí liên kết ví; type 33 hiện Tổng phí chia sẻ vật tư";
    public static final String TRANSACTION_FEE_017 = "TRANSACTION-FEE-017 - Phí kết nối: Tổng doanh thu bằng Đã thu cộng Công nợ và tổng hai tỷ lệ bằng 100%";
    public static final String TRANSACTION_FEE_018 = "TRANSACTION-FEE-018 - Phí kết nối: Biểu đồ Doanh thu theo ngày có khoảng ngày và nút Tuần này, Tháng này, Tuỳ chỉnh";
    public static final String TRANSACTION_FEE_019 = "TRANSACTION-FEE-019 - Phí và doanh thu: Bộ lọc Xuất hoá đơn của từng loại có đúng Tất cả, Có và Không";
    public static final String TRANSACTION_FEE_020 = "TRANSACTION-FEE-020 - Phí và doanh thu: Chọn Xuất hoá đơn Có lọc dữ liệu hoặc hiện rỗng hợp lệ và giữ đúng type=8/9/33";
    public static final String TRANSACTION_FEE_021 = "TRANSACTION-FEE-021 - Phí và doanh thu: Chọn Xuất hoá đơn Không lọc dữ liệu hoặc hiện rỗng hợp lệ và giữ đúng type=8/9/33";
    public static final String TRANSACTION_FEE_022 = "TRANSACTION-FEE-022 - Phí và doanh thu: Bộ lọc ngày không cho chọn ngày tương lai";
    public static final String TRANSACTION_FEE_023 = "TRANSACTION-FEE-023 - Phí và doanh thu: Bộ lọc ngày mặc định 00:00-23:59 và chưa chọn ngày thì khóa Áp dụng";
    public static final String TRANSACTION_FEE_024 = "TRANSACTION-FEE-024 - Phí và doanh thu: Từ khoá không tồn tại hiện Chưa có dữ liệu, Reset khôi phục danh sách và type=8/9/33";
    public static final String TRANSACTION_FEE_025 = "TRANSACTION-FEE-025 - Phí và doanh thu: Ngày tạo trên từng type=8/9/33 sắp xếp đúng tăng dần rồi giảm dần";
    public static final String TRANSACTION_FEE_026 = "TRANSACTION-FEE-026 - Phí và doanh thu: Chi tiết của từng loại khớp loại, trạng thái, số tiền và thời gian của dòng đã mở";
    public static final String TRANSACTION_FEE_027 = "TRANSACTION-FEE-027 - Phí và doanh thu: URL chi tiết có đúng một id và giữ type=8/9/33";
    public static final String TRANSACTION_FEE_028 = "TRANSACTION-FEE-028 - Phí và doanh thu: Nút X đóng chi tiết, xoá id và giữ type=8/9/33";
    public static final String TRANSACTION_FEE_029 = "TRANSACTION-FEE-029 - Phí và doanh thu: Refresh khi mở chi tiết Phí kết nối giữ nguyên id và drawer";
    public static final String TRANSACTION_FEE_030 = "TRANSACTION-FEE-030 - Phí và doanh thu: Back đóng chi tiết Phí kết nối, Forward mở lại đúng id và drawer";
    public static final String TRANSACTION_FEE_031 = "TRANSACTION-FEE-031 - Phí liên kết ví: Tổng tiền và tổng giao dịch bằng tổng Hoàn thành, Đang chờ, Từ chối; tỷ lệ bằng 100%";
    public static final String TRANSACTION_FEE_032 = "TRANSACTION-FEE-032 - Phí chia sẻ vật tư: Hiển thị Tổng tiền thu và Tổng số đơn hợp lệ";
    public static final String TRANSACTION_FEE_033 = "TRANSACTION-FEE-033 - Chi tiết phí: Type 8 hiện Người gửi và Mã đơn; type 9 hiện Người nhận, số dư và cổng; type 33 hiện Người gửi, biến động và Mã đơn";
    public static final String TRANSACTION_FEE_034 = "TRANSACTION-FEE-034 - Chi tiết phí: Nhấn Escape đóng drawer, xoá id và giữ đúng type=8/9/33";
    public static final String TRANSACTION_FEE_035 = "TRANSACTION-FEE-035 - Chi tiết phí: Deep-link mở lại đúng id, type và nội dung trên cả type=8/9/33";
    public static final String TRANSACTION_FEE_036 = "TRANSACTION-FEE-036 - Chi tiết phí: Link người dùng hoặc thợ và toàn bộ link dòng tiền có URL hợp lệ, không trùng";
    public static final String TRANSACTION_FEE_037 = "TRANSACTION-FEE-037 - Chi tiết phí: Dòng tiền type=8/9/33 tải xong; nếu có số tổng thì Tổng vào, Tổng ra và Dòng tiền ròng hiển thị đồng bộ";
    public static final String TRANSACTION_FEE_038 = "TRANSACTION-FEE-038 - Chi tiết Phí kết nối: Dòng tiền đánh dấu đúng giao dịch đang xem và khớp loại, số tiền nguồn";
    public static final String TRANSACTION_FEE_039 = "TRANSACTION-FEE-039 - Chi tiết Phí liên kết ví và Phí chia sẻ vật tư: Xem thêm làm tăng số giao dịch dòng tiền";
    public static final String TRANSACTION_FEE_040 = "TRANSACTION-FEE-040 - Chi tiết phí: Mở dòng giao dịch khác đổi id, dòng nguồn và nội dung trên type=8/9/33";
    public static final String TRANSACTION_FEE_041 = "TRANSACTION-FEE-041 - Chi tiết Phí liên kết ví: Dòng Thành công và Thất bại mở đúng trạng thái, loại, cổng rồi đóng về type=9";
    public static final String TRANSACTION_FEE_042 = "TRANSACTION-FEE-042 - Chi tiết Phí kết nối: Mở và đóng giao dịch ở trang 2 vẫn giữ trang 2, danh sách và type=8";
    public static final String TRANSACTION_FEE_043 = "TRANSACTION-FEE-043 - Chi tiết Phí kết nối: Người gửi có tên, SĐT, worker ID, tiêu đề dòng tiền khớp; Mã đơn mở đúng đơn trong tab mới";
    public static final String TRANSACTION_FEE_044 = "TRANSACTION-FEE-044 - Chi tiết Phí kết nối: Dòng tiền ròng bằng Tổng vào cộng Tổng ra có dấu";
    public static final String TRANSACTION_FEE_045 = "TRANSACTION-FEE-045 - Chi tiết Phí kết nối: Timeline có đúng một dòng đang xem khớp id, loại, trạng thái, số tiền và thời gian nguồn";
    public static final String TRANSACTION_FEE_046 = "TRANSACTION-FEE-046 - Chi tiết Phí kết nối: Mỗi dòng timeline có link id duy nhất, mở tab mới, đủ số tiền và thời gian";
    public static final String TRANSACTION_FEE_047 = "TRANSACTION-FEE-047 - Điều hướng Phí và doanh thu: Trên type=8/9/33, click Người gửi hoặc người nhận mở đúng hồ sơ user/thợ theo ID trong tab mới rồi quay lại drawer nguồn";
    public static final String TRANSACTION_FEE_048 = "TRANSACTION-FEE-048 - Điều hướng Phí và doanh thu: Trên type=8/33, click Mã đơn dịch vụ mở đúng đơn theo ID trong tab mới rồi quay lại drawer nguồn";
    public static final String TRANSACTION_FEE_049 = "TRANSACTION-FEE-049 - Điều hướng Phí và doanh thu: Trên type=8/9/33, click giao dịch timeline mở đúng chi tiết ID khác trong tab mới rồi quay lại drawer nguồn";
    public static final String TRANSACTION_FEE_050 = "TRANSACTION-FEE-050 - Tổng quan Phí kết nối: Hover biểu đồ doanh thu hiển thị tooltip có ngày và số tiền";
    public static final String TRANSACTION_FEE_051 = "TRANSACTION-FEE-051 - Bộ lọc Phí và doanh thu: Trên type=8/9/33, chọn khoảng hai ngày chỉ hiển thị giao dịch nằm trong cả ngày bắt đầu và kết thúc";
    public static final String TRANSACTION_FEE_052 = "TRANSACTION-FEE-052 - Bộ lọc Phí và doanh thu: Trên type=8/9/33, chọn một ngày dùng 00:00-23:59 và chỉ hiển thị giao dịch của ngày đó";
    public static final String TRANSACTION_FEE_053 = "TRANSACTION-FEE-053 - Bộ lọc Phí kết nối: Chọn khoảng một phút chỉ hiển thị giao dịch có ngày giờ nằm trong khoảng đã chọn";
    public static final String TRANSACTION_FEE_054 = "TRANSACTION-FEE-054 - Bộ lọc Phí kết nối: Chọn ngày rồi đóng lịch không bấm Áp dụng giữ nguyên khoảng ngày và danh sách";
    public static final String TRANSACTION_FEE_055 = "TRANSACTION-FEE-055 - Bộ lọc Phí kết nối: Xóa riêng khoảng ngày đã áp dụng khôi phục tổng dữ liệu và ẩn nút xóa ngày";
    public static final String TRANSACTION_FEE_056 = "TRANSACTION-FEE-056 - Bộ lọc Phí và doanh thu: Trên type=8/9/33, kết hợp Tên/SĐT thật với một ngày chỉ hiển thị dòng khớp cả người dùng và ngày";
    public static final String TRANSACTION_FEE_057 = "TRANSACTION-FEE-057 - Bộ lọc Phí kết nối: Chuyển Xuất hóa đơn Có sang Không rồi Tất cả cập nhật lựa chọn và khôi phục danh sách ban đầu";
    public static final String TRANSACTION_FEE_058 = "TRANSACTION-FEE-058 - Bộ lọc Phí và doanh thu: Trên type=8/9/33, Reset xóa đồng thời Tên/SĐT, Xuất hóa đơn Có và ngày nhưng giữ đúng loại";
    public static final String TRANSACTION_FEE_059 = "TRANSACTION-FEE-059 - Bộ lọc Phí kết nối: Tên/SĐT và ngày vẫn giữ nguyên sau khi mở rồi đóng chi tiết giao dịch";
    public static final String TRANSACTION_FEE_060 = "TRANSACTION-FEE-060 - Điều hướng Phí kết nối: Click cột Loại giao dịch và Trạng thái không hỗ trợ sort giữ nguyên danh sách";
    public static final String TRANSACTION_FEE_061 = "TRANSACTION-FEE-061 - Điều hướng Phí kết nối: Trang 2 có danh sách khác trang 1 và quay lại trang 1 khôi phục đúng dữ liệu";
    public static final String TRANSACTION_FEE_062 = "TRANSACTION-FEE-062 - Điều hướng Phí kết nối: Trang 1 khóa Previous; Next sang trang 2 cập nhật dấu active; Previous quay lại trang 1";
    public static final String TRANSACTION_FEE_063 = "TRANSACTION-FEE-063 - Điều hướng Phí kết nối: Trang cuối khóa Next và hiển thị từ 1 đến 20 giao dịch";
    public static final String TRANSACTION_FEE_064 = "TRANSACTION-FEE-064 - Điều hướng Phí kết nối: Trang 1 và trang 2 không chứa giao dịch trùng nhau";
    public static final String TRANSACTION_FEE_065 = "TRANSACTION-FEE-065 - Điều hướng Phí kết nối: Sort Số tiền giảm dần giữ đúng thứ tự trên trang 1, trang 2 và khi quay lại trang 1";
    public static final String TRANSACTION_FEE_066 = "TRANSACTION-FEE-066 - Điều hướng Phí kết nối: Sort Ngày tạo giảm dần giữ đúng thứ tự trên trang 1, trang 2 và khi quay lại trang 1";
    public static final String TRANSACTION_FEE_067 = "TRANSACTION-FEE-067 - Điều hướng Phí kết nối: Từ trang 2 chọn Xuất hóa đơn Có quay về trang 1, cập nhật lựa chọn và giữ type=8";
    public static final String TRANSACTION_FEE_068 = "TRANSACTION-FEE-068 - Điều hướng Phí kết nối: Mở rồi đóng chi tiết từ trang 2 giữ nguyên trang 2, danh sách và loại Phí kết nối đang chọn";
    public static final String TRANSACTION_FEE_069 = "TRANSACTION-FEE-069 - Điều hướng Phí kết nối: Reset sau sort Số tiền giảm dần khôi phục thứ tự mặc định và trang 1";
    public static final String TRANSACTION_FEE_070 = "TRANSACTION-FEE-070 - Điều hướng Phí kết nối: Reset từ trang 2 quay về trang 1 và giữ type=8";
    public static final String TRANSACTION_FEE_071 = "TRANSACTION-FEE-071 - Bộ lọc chart Phí kết nối: Chọn Tuần này hiển thị đúng từ Thứ Hai đến Chủ Nhật và đủ bảy nhãn ngày trên trục X";
    public static final String TRANSACTION_FEE_072 = "TRANSACTION-FEE-072 - Bộ lọc chart Phí kết nối: Chọn Tháng này hiển thị từ ngày 01 đến ngày cuối tháng và trục X đúng tháng hiện tại";
    public static final String TRANSACTION_FEE_073 = "TRANSACTION-FEE-073 - Bộ lọc chart Phí kết nối: Chọn Tuỳ chỉnh hiện ô khoảng ngày, mở lịch và khóa toàn bộ ngày sau hôm nay";
    public static final String TRANSACTION_FEE_074 = "TRANSACTION-FEE-074 - Bộ lọc chart Phí kết nối: Chọn ngày 01-05 của tháng trước cập nhật đúng input, dòng mô tả, năm nhãn trục X và tooltip doanh thu";
    public static final String TRANSACTION_FEE_075 = "TRANSACTION-FEE-075 - Bộ lọc chart Phí kết nối: Chuyển Tuần này sang Tháng này, Tuỳ chỉnh rồi về Tuần này cập nhật đúng active và không đổi bảng giao dịch";
    public static final String TRANSACTION_FEE_076 = "TRANSACTION-FEE-076 - Tổng quan Phí và doanh thu: Type 8/9/33 có tổng số giao dịch hoặc đơn bằng Tổng hiển thị của danh sách";
    public static final String TRANSACTION_FEE_077 = "TRANSACTION-FEE-077 - Tổng quan Phí kết nối: Biểu đồ tròn có đúng phần Đã thu màu xanh và Công nợ màu đỏ tương ứng số tiền khác 0";
    public static final String TRANSACTION_FEE_078 = "TRANSACTION-FEE-078 - Tổng quan Phí kết nối: Tỷ lệ Đã thu và Công nợ khớp từng số tiền chia Tổng doanh thu, làm tròn một chữ số";
    public static final String TRANSACTION_FEE_079 = "TRANSACTION-FEE-079 - Tổng quan Phí kết nối: Mở Công nợ thợ hiển thị cột Thợ, Số tiền nợ, Ngày nợ; dòng có worker ID, tiền âm, ngày và số ngày nợ hợp lệ";
    public static final String TRANSACTION_FEE_080 = "TRANSACTION-FEE-080 - Tổng quan Phí kết nối: Trong Công nợ thợ, sort Số tiền nợ và số ngày đã nợ đủ hai chiều tăng dần, giảm dần";
    public static final String TRANSACTION_FEE_081 = "TRANSACTION-FEE-081 - Tổng quan Phí kết nối: Công nợ thợ sang trang 2 đổi dữ liệu, về trang 1 khôi phục danh sách rồi đóng modal giữ type=8";
    public static final String TRANSACTION_FEE_082 = "TRANSACTION-FEE-082 - Tổng quan Phí liên kết ví: Hai biểu đồ tiền và số giao dịch có đúng phần trạng thái khác 0 cùng màu Hoàn thành, Đang chờ, Từ chối";
    public static final String TRANSACTION_FEE_084 = "TRANSACTION-FEE-084 - Tổng quan Phí và doanh thu: Chuyển type=8 sang 9 và 33 chỉ hiển thị đúng khối tổng quan của loại hiện tại, không sót loại trước";
    public static final String TRANSACTION_FEE_085 = "TRANSACTION-FEE-085 - Tổng quan Phí và doanh thu: Refresh từng type=8/9/33 giữ đúng route, loại đang chọn và các khối tổng quan";
    public static final String TRANSACTION_FEE_086 = "TRANSACTION-FEE-086 - Bộ lọc hóa đơn: Trên Phí kết nối và Phí chia sẻ vật tư, chọn Có/Không rồi mở các đơn mẫu xác nhận thực tế có/không có thông tin hóa đơn";
    public static final String TRANSACTION_FEE_087 = "TRANSACTION-FEE-087 - Chi tiết phí: Trên type=8/9/33, mở từng trạng thái khác nhau đang có trên danh sách và đối chiếu trạng thái trong drawer";
    public static final String TRANSACTION_FEE_088 = "TRANSACTION-FEE-088 - Tổng quan Phí kết nối: Từ Công nợ thợ, click thợ mở đúng hồ sơ theo ID trong tab mới rồi quay lại modal";
    public static final String TRANSACTION_FEE_089 = "TRANSACTION-FEE-089 - Tổng quan Phí chia sẻ vật tư: Tổng tiền thu bằng tổng Số tiền của toàn bộ giao dịch trên tất cả trang";
    public static final String TRANSACTION_FEE_090 = "TRANSACTION-FEE-090 - Deep-link Phí và doanh thu: type không hợp lệ không hiển thị drawer sai và không đánh dấu nhầm type=8/9/33";
    public static final String TRANSACTION_FEE_091 = "TRANSACTION-FEE-091 - Deep-link Phí và doanh thu: id giao dịch không tồn tại không mở drawer chi tiết sai, vẫn giữ Phí kết nối";
    public static final String TRANSACTION_FEE_092 = "TRANSACTION-FEE-092 - Deep-link Phí và doanh thu: URL chỉ có tab=fee không type mở loại mặc định hợp lệ và không tự mở drawer";
    public static final String TRANSACTION_FEE_093 = "TRANSACTION-FEE-093 - Deep-link Phí và doanh thu: ID thuộc Phí liên kết ví không được hiển thị dưới type Phí kết nối sai";

    public static final String TRANSACTION_INSURANCE_001 = "TRANSACTION-INSURANCE-001 - VT Care: Hiển thị đầy đủ các loại giao dịch con";
    public static final String TRANSACTION_INSURANCE_002 = "TRANSACTION-INSURANCE-002 - Dropdown VT Care: Lần lượt mở trực tiếp type=25 Trừ phí và type=26 Hoàn phí, route và nhãn đang chọn đều chính xác";
    public static final String TRANSACTION_INSURANCE_003 = "TRANSACTION-INSURANCE-003 - VT Care: Hiển thị đúng bộ lọc và cột dữ liệu";
    public static final String TRANSACTION_INSURANCE_004 = "TRANSACTION-INSURANCE-004 - VT Care: Dòng giao dịch có định dạng hợp lệ";
    public static final String TRANSACTION_INSURANCE_005 = "TRANSACTION-INSURANCE-005 - VT Care: Tìm kiếm người dùng và Reset khôi phục dữ liệu";
    public static final String TRANSACTION_INSURANCE_006 = "TRANSACTION-INSURANCE-006 - Bộ lọc VT Care: Trạng thái có Đang chờ/Thành công/Thất bại và Cổng thanh toán có MOMO/PAYPAL/ONEPAY/BANKING/NEOX";
    public static final String TRANSACTION_INSURANCE_007 = "TRANSACTION-INSURANCE-007 - VT Care: Sắp xếp số tiền tăng và giảm dần";
    public static final String TRANSACTION_INSURANCE_008 = "TRANSACTION-INSURANCE-008 - Chi tiết VT Care: Lần lượt mở và đóng giao dịch type=25 Trừ phí và type=26 Hoàn phí, giữ đúng loại đang chọn";
    public static final String TRANSACTION_INSURANCE_009 = "TRANSACTION-INSURANCE-009 - VT Care: Phân trang và Reset giữ đúng tab";
    public static final String TRANSACTION_INSURANCE_010 = "TRANSACTION-INSURANCE-010 - VT Care: Xuất Excel cho loại giao dịch đang chọn";
    public static final String TRANSACTION_INSURANCE_011 = "TRANSACTION-INSURANCE-011 - Dropdown VT Care: Hiển thị đúng Trừ phí type=25, Hoàn phí type=26 và chỉ một loại được chọn";
    public static final String TRANSACTION_INSURANCE_012 = "TRANSACTION-INSURANCE-012 - Dropdown VT Care: Trong một flow chọn type=25 Trừ phí và type=26 Hoàn phí, mỗi lần đều cập nhật route, nhãn, dấu chọn duy nhất và tự đóng menu";
    public static final String TRANSACTION_INSURANCE_013 = "TRANSACTION-INSURANCE-013 - Dropdown VT Care: Bấm lại trigger đóng menu và vẫn giữ Trừ phí VT Care type=25";
    public static final String TRANSACTION_INSURANCE_014 = "TRANSACTION-INSURANCE-014 - Dropdown VT Care: Nhấn Escape đóng menu và vẫn giữ Trừ phí VT Care type=25";
    public static final String TRANSACTION_INSURANCE_034 = "TRANSACTION-INSURANCE-034 - Dropdown VT Care: Click ra ngoài đóng menu, không đổi type=25 Trừ phí, URL và dữ liệu đang xem";
    public static final String TRANSACTION_INSURANCE_035 = "TRANSACTION-INSURANCE-035 - Dropdown VT Care: Từ type=25 dùng Arrow Down và Enter chọn type=26, menu đóng và focus trở lại trigger";
    public static final String TRANSACTION_INSURANCE_036 = "TRANSACTION-INSURANCE-036 - Dropdown VT Care: Chuyển type=25 sang type=26 rồi về type=25 cập nhật đúng route, nhãn và loại dữ liệu mỗi lần";
    public static final String TRANSACTION_INSURANCE_037 = "TRANSACTION-INSURANCE-037 - Dropdown VT Care: Refresh tại type=25 và type=26 giữ nguyên route, nhãn và đúng một option được chọn";
    public static final String TRANSACTION_INSURANCE_038 = "TRANSACTION-INSURANCE-038 - Dropdown VT Care: URL type=999999 giữ nhãn nhóm VT Care, không hiển thị nhầm Trừ phí/Hoàn phí và không chọn option nào";
    public static final String TRANSACTION_INSURANCE_015 = "TRANSACTION-INSURANCE-015 - Tổng quan VT Care: Trên type=25/26, tổng tiền và tổng giao dịch bằng tổng Hoàn thành, Đang chờ, Từ chối; tỷ lệ bằng 100%";
    public static final String TRANSACTION_INSURANCE_016 = "TRANSACTION-INSURANCE-016 - Tổng quan VT Care: Trên type=25/26, Tổng số giao dịch bằng Tổng hiển thị của toàn bộ kết quả";
    public static final String TRANSACTION_INSURANCE_017 = "TRANSACTION-INSURANCE-017 - Bộ lọc VT Care: Trên type=25/26, chọn từng Trạng thái và Cổng thanh toán giữ đúng loại, trả dữ liệu hoặc trạng thái rỗng hợp lệ";
    public static final String TRANSACTION_INSURANCE_018 = "TRANSACTION-INSURANCE-018 - Bộ lọc ngày VT Care: Khóa ngày tương lai, mặc định 00:00-23:59 và chưa chọn ngày thì khóa Áp dụng";
    public static final String TRANSACTION_INSURANCE_019 = "TRANSACTION-INSURANCE-019 - Bộ lọc ngày VT Care: Trên type=25/26, chọn một ngày chỉ trả giao dịch trong 00:00-23:59 của ngày đó";
    public static final String TRANSACTION_INSURANCE_020 = "TRANSACTION-INSURANCE-020 - Tìm kiếm VT Care: Trên type=25/26, từ khóa không tồn tại hiện Chưa có dữ liệu và Reset khôi phục danh sách";
    public static final String TRANSACTION_INSURANCE_021 = "TRANSACTION-INSURANCE-021 - Điều hướng VT Care: Trên type=25/26, sort Ngày tạo tăng dần rồi giảm dần đúng thứ tự";
    public static final String TRANSACTION_INSURANCE_022 = "TRANSACTION-INSURANCE-022 - Điều hướng Trừ phí VT Care: Sang trang 2 đổi dữ liệu và quay lại trang 1 khôi phục đúng danh sách";
    public static final String TRANSACTION_INSURANCE_023 = "TRANSACTION-INSURANCE-023 - Chi tiết VT Care: Trên type=25/26, drawer khớp trạng thái, loại và các trường giao dịch của dòng nguồn";
    public static final String TRANSACTION_INSURANCE_024 = "TRANSACTION-INSURANCE-024 - Chi tiết VT Care: Trên type=25/26, đóng rồi mở lại deep-link khôi phục đúng drawer và URL";
    public static final String TRANSACTION_INSURANCE_025 = "TRANSACTION-INSURANCE-025 - Chi tiết VT Care: Trên type=25/26, nút X đóng drawer, xóa id và giữ đúng subtype";
    public static final String TRANSACTION_INSURANCE_026 = "TRANSACTION-INSURANCE-026 - Chi tiết Trừ phí VT Care type=25: hiển thị người gửi, biến động số dư, tổng vào, tổng ra, dòng tiền ròng và đúng một giao dịch đang xem";
    public static final String TRANSACTION_INSURANCE_027 = "TRANSACTION-INSURANCE-027 - Chi tiết VT Care: Trên type=25/26, dòng tiền ròng bằng Tổng vào cộng Tổng ra";
    public static final String TRANSACTION_INSURANCE_028 = "TRANSACTION-INSURANCE-028 - Chi tiết VT Care: Trên type=25/26, link người gửi mở đúng hồ sơ ở tab mới rồi quay lại nguyên drawer";
    public static final String TRANSACTION_INSURANCE_029 = "TRANSACTION-INSURANCE-029 - Chi tiết VT Care: Trên type=25/26, link timeline mở đúng giao dịch ID khác ở tab mới rồi quay lại nguyên drawer";
    public static final String TRANSACTION_INSURANCE_030 = "TRANSACTION-INSURANCE-030 - Chi tiết VT Care: Trên type=25/26, nhấn Escape đóng drawer, xóa id và giữ đúng subtype";
    public static final String TRANSACTION_INSURANCE_031 = "TRANSACTION-INSURANCE-031 - Chi tiết VT Care: Trên type=25/26, refresh deep-link vẫn giữ đúng drawer và subtype";
    public static final String TRANSACTION_INSURANCE_032 = "TRANSACTION-INSURANCE-032 - Chi tiết VT Care: Trên type=25/26, Back đóng drawer và Forward mở lại đúng giao dịch";
    public static final String TRANSACTION_INSURANCE_033 = "TRANSACTION-INSURANCE-033 - Chi tiết Trừ phí VT Care type=25 trạng thái Thành công: nút Hủy hiển thị, nút Từ chối có trong DOM nhưng bị ẩn";

    public static final String TRANSACTION_ASSISTANT_001 = "TRANSACTION-ASSISTANT-001 - Thợ phụ: Hiển thị đầy đủ các loại giao dịch con";
    public static final String TRANSACTION_ASSISTANT_002 = "TRANSACTION-ASSISTANT-002 - Thợ phụ: Mở đúng route và đánh dấu loại đang chọn";
    public static final String TRANSACTION_ASSISTANT_003 = "TRANSACTION-ASSISTANT-003 - Thợ phụ: Hiển thị đúng bộ lọc và cột dữ liệu";
    public static final String TRANSACTION_ASSISTANT_004 = "TRANSACTION-ASSISTANT-004 - Thợ phụ: Dòng giao dịch có định dạng hợp lệ";
    public static final String TRANSACTION_ASSISTANT_005 = "TRANSACTION-ASSISTANT-005 - Thợ phụ: Tìm kiếm người dùng và Reset khôi phục dữ liệu";
    public static final String TRANSACTION_ASSISTANT_006 = "TRANSACTION-ASSISTANT-006 - Thợ phụ: Bộ lọc hiển thị lựa chọn và giữ đúng tab";
    public static final String TRANSACTION_ASSISTANT_007 = "TRANSACTION-ASSISTANT-007 - Thợ phụ: Sắp xếp số tiền tăng và giảm dần";
    public static final String TRANSACTION_ASSISTANT_008 = "TRANSACTION-ASSISTANT-008 - Thợ phụ: Mở và đóng chi tiết giao dịch";
    public static final String TRANSACTION_ASSISTANT_009 = "TRANSACTION-ASSISTANT-009 - Thợ phụ: Phân trang và Reset giữ đúng tab";
    public static final String TRANSACTION_ASSISTANT_010 = "TRANSACTION-ASSISTANT-010 - Thợ phụ: Xuất Excel cho loại giao dịch đang chọn";
    public static final String TRANSACTION_ASSISTANT_011 = "TRANSACTION-ASSISTANT-011 - Thợ phụ: Dữ liệu đúng với từng loại giao dịch con";
    public static final String TRANSACTION_ASSISTANT_012 = "TRANSACTION-ASSISTANT-012 - Thợ phụ: Hiển thị đầy đủ lựa chọn trạng thái";
    public static final String TRANSACTION_ASSISTANT_013 = "TRANSACTION-ASSISTANT-013 - Thợ phụ: Hiển thị đầy đủ lựa chọn cổng thanh toán";
    public static final String TRANSACTION_ASSISTANT_014 = "TRANSACTION-ASSISTANT-014 - Thợ phụ: Lọc chính xác theo trạng thái của dữ liệu thật";
    public static final String TRANSACTION_ASSISTANT_015 = "TRANSACTION-ASSISTANT-015 - Thợ phụ: Kết hợp bộ lọc trạng thái và cổng thanh toán";
    public static final String TRANSACTION_ASSISTANT_016 = "TRANSACTION-ASSISTANT-016 - Thợ phụ: Kiểm tra lần lượt mọi lựa chọn trạng thái";
    public static final String TRANSACTION_ASSISTANT_017 = "TRANSACTION-ASSISTANT-017 - Thợ phụ: Kiểm tra lần lượt mọi lựa chọn cổng thanh toán";
    public static final String TRANSACTION_ASSISTANT_018 = "TRANSACTION-ASSISTANT-018 - Thợ phụ: Đóng bộ lọc không làm thay đổi dữ liệu";
    public static final String TRANSACTION_ASSISTANT_019 = "TRANSACTION-ASSISTANT-019 - Thợ phụ: Không cho chọn ngày giao dịch trong tương lai";
    public static final String TRANSACTION_ASSISTANT_020 = "TRANSACTION-ASSISTANT-020 - Thợ phụ: Bộ lọc ngày có giờ mặc định và yêu cầu chọn ngày";
    public static final String TRANSACTION_ASSISTANT_021 = "TRANSACTION-ASSISTANT-021 - Thợ phụ: Lọc chính xác giao dịch trong một ngày";
    public static final String TRANSACTION_ASSISTANT_022 = "TRANSACTION-ASSISTANT-022 - Thợ phụ: Bộ lọc được giữ khi mở và đóng chi tiết";
    public static final String TRANSACTION_ASSISTANT_023 = "TRANSACTION-ASSISTANT-023 - Thợ phụ: Từ khóa không khớp hiển thị trạng thái rỗng";
    public static final String TRANSACTION_ASSISTANT_024 = "TRANSACTION-ASSISTANT-024 - Thợ phụ: Reset từ trạng thái rỗng khôi phục dữ liệu và giữ loại";
    public static final String TRANSACTION_ASSISTANT_025 = "TRANSACTION-ASSISTANT-025 - Thợ phụ: Tổng và phân trang cập nhật theo trạng thái";
    public static final String TRANSACTION_ASSISTANT_026 = "TRANSACTION-ASSISTANT-026 - Thợ phụ: Lọc chính xác theo khoảng ngày giờ của giao dịch";
    public static final String TRANSACTION_ASSISTANT_027 = "TRANSACTION-ASSISTANT-027 - Thợ phụ: Sắp xếp vẫn chính xác sau khi lọc trạng thái";
    public static final String TRANSACTION_ASSISTANT_028 = "TRANSACTION-ASSISTANT-028 - Thợ phụ: Xuất Excel sau khi lọc trạng thái";
    public static final String TRANSACTION_ASSISTANT_029 = "TRANSACTION-ASSISTANT-029 - Thợ phụ: Trigger mở đúng menu được liên kết";
    public static final String TRANSACTION_ASSISTANT_030 = "TRANSACTION-ASSISTANT-030 - Thợ phụ: Option có đúng key và trạng thái lựa chọn";
    public static final String TRANSACTION_ASSISTANT_031 = "TRANSACTION-ASSISTANT-031 - Thợ phụ: Chọn Tiền phạt cập nhật route và trạng thái";
    public static final String TRANSACTION_ASSISTANT_032 = "TRANSACTION-ASSISTANT-032 - Thợ phụ: Escape đóng dropdown và giữ loại đang chọn";
    public static final String TRANSACTION_ASSISTANT_033 = "TRANSACTION-ASSISTANT-033 - Thợ phụ: Chi tiết hiển thị đầy đủ các khu vực thông tin";
    public static final String TRANSACTION_ASSISTANT_034 = "TRANSACTION-ASSISTANT-034 - Thợ phụ: Chi tiết khớp loại giao dịch của từng nhóm con";
    public static final String TRANSACTION_ASSISTANT_035 = "TRANSACTION-ASSISTANT-035 - Thợ phụ: Chi tiết khớp trạng thái của dòng đã chọn";
    public static final String TRANSACTION_ASSISTANT_036 = "TRANSACTION-ASSISTANT-036 - Thợ phụ: Chi tiết khớp số tiền của dòng đã chọn";
    public static final String TRANSACTION_ASSISTANT_037 = "TRANSACTION-ASSISTANT-037 - Thợ phụ: Chi tiết khớp thời gian của dòng đã chọn";
    public static final String TRANSACTION_ASSISTANT_038 = "TRANSACTION-ASSISTANT-038 - Thợ phụ: Chi tiết có liên kết người gửi hợp lệ";
    public static final String TRANSACTION_ASSISTANT_039 = "TRANSACTION-ASSISTANT-039 - Thợ phụ: URL chi tiết có đúng một ID và giữ loại giao dịch";
    public static final String TRANSACTION_ASSISTANT_040 = "TRANSACTION-ASSISTANT-040 - Thợ phụ: Refresh giữ nguyên chi tiết đang mở";
    public static final String TRANSACTION_ASSISTANT_041 = "TRANSACTION-ASSISTANT-041 - Thợ phụ: Deep link mở lại đúng chi tiết giao dịch";
    public static final String TRANSACTION_ASSISTANT_042 = "TRANSACTION-ASSISTANT-042 - Thợ phụ: Back và Forward đóng rồi mở lại chi tiết";
    public static final String TRANSACTION_ASSISTANT_043 = "TRANSACTION-ASSISTANT-043 - Thợ phụ: Chi tiết hiển thị tổng dòng tiền";
    public static final String TRANSACTION_ASSISTANT_044 = "TRANSACTION-ASSISTANT-044 - Thợ phụ: Lịch sử dòng tiền tải xong không còn trạng thái chờ";
    public static final String TRANSACTION_ASSISTANT_045 = "TRANSACTION-ASSISTANT-045 - Thợ phụ: Xem thêm tải tới giao dịch đang xem";
    public static final String TRANSACTION_ASSISTANT_046 = "TRANSACTION-ASSISTANT-046 - Thợ phụ: Giao dịch đang xem khớp dữ liệu nguồn";
    public static final String TRANSACTION_ASSISTANT_047 = "TRANSACTION-ASSISTANT-047 - Thợ phụ: Mở dòng khác cập nhật URL và nội dung chi tiết";
    public static final String TRANSACTION_ASSISTANT_048 = "TRANSACTION-ASSISTANT-048 - Thợ phụ: Liên kết dòng tiền mở đúng giao dịch liên quan";
    public static final String TRANSACTION_ASSISTANT_049 = "TRANSACTION-ASSISTANT-049 - Thợ phụ: Icon đóng loại bỏ ID và giữ route hiện tại";
    public static final String TRANSACTION_ASSISTANT_050 = "TRANSACTION-ASSISTANT-050 - Tiền phạt: Hiển thị đúng bộ lọc và cột dữ liệu";
    public static final String TRANSACTION_ASSISTANT_051 = "TRANSACTION-ASSISTANT-051 - Tiền phạt: Dòng giao dịch có định dạng hợp lệ";
    public static final String TRANSACTION_ASSISTANT_052 = "TRANSACTION-ASSISTANT-052 - Tiền phạt: Tìm kiếm người dùng và Reset khôi phục dữ liệu";
    public static final String TRANSACTION_ASSISTANT_053 = "TRANSACTION-ASSISTANT-053 - Tiền phạt: Bộ lọc hiển thị lựa chọn và giữ đúng loại";
    public static final String TRANSACTION_ASSISTANT_054 = "TRANSACTION-ASSISTANT-054 - Tiền phạt: Lọc chính xác theo trạng thái của dữ liệu thật";
    public static final String TRANSACTION_ASSISTANT_055 = "TRANSACTION-ASSISTANT-055 - Tiền phạt: Kết hợp bộ lọc trạng thái và cổng thanh toán";
    public static final String TRANSACTION_ASSISTANT_056 = "TRANSACTION-ASSISTANT-056 - Tiền phạt: Kiểm tra lần lượt mọi lựa chọn trạng thái";
    public static final String TRANSACTION_ASSISTANT_057 = "TRANSACTION-ASSISTANT-057 - Tiền phạt: Kiểm tra lần lượt mọi lựa chọn cổng thanh toán";
    public static final String TRANSACTION_ASSISTANT_058 = "TRANSACTION-ASSISTANT-058 - Tiền phạt: Đóng bộ lọc không làm thay đổi dữ liệu";
    public static final String TRANSACTION_ASSISTANT_059 = "TRANSACTION-ASSISTANT-059 - Tiền phạt: Lọc chính xác giao dịch trong một ngày";
    public static final String TRANSACTION_ASSISTANT_060 = "TRANSACTION-ASSISTANT-060 - Tiền phạt: Từ khóa không khớp hiển thị trạng thái rỗng";
    public static final String TRANSACTION_ASSISTANT_061 = "TRANSACTION-ASSISTANT-061 - Tiền phạt: Reset từ trạng thái rỗng khôi phục dữ liệu và giữ loại";
    public static final String TRANSACTION_ASSISTANT_062 = "TRANSACTION-ASSISTANT-062 - Tiền phạt: Tổng và phân trang cập nhật theo trạng thái";
    public static final String TRANSACTION_ASSISTANT_063 = "TRANSACTION-ASSISTANT-063 - Tiền phạt: Lọc chính xác theo khoảng ngày giờ của giao dịch";
    public static final String TRANSACTION_ASSISTANT_064 = "TRANSACTION-ASSISTANT-064 - Tiền phạt: Sắp xếp số tiền tăng và giảm dần";
    public static final String TRANSACTION_ASSISTANT_065 = "TRANSACTION-ASSISTANT-065 - Tiền phạt: Phân trang và Reset giữ đúng loại";
    public static final String TRANSACTION_ASSISTANT_066 = "TRANSACTION-ASSISTANT-066 - Tiền phạt: Sắp xếp vẫn chính xác sau khi lọc trạng thái";
    public static final String TRANSACTION_ASSISTANT_067 = "TRANSACTION-ASSISTANT-067 - Tiền phạt: Mở và đóng chi tiết giao dịch";
    public static final String TRANSACTION_ASSISTANT_068 = "TRANSACTION-ASSISTANT-068 - Tiền phạt: Bộ lọc được giữ khi mở và đóng chi tiết";
    public static final String TRANSACTION_ASSISTANT_069 = "TRANSACTION-ASSISTANT-069 - Tiền phạt: Chi tiết hiển thị đầy đủ các khu vực thông tin";
    public static final String TRANSACTION_ASSISTANT_073 = "TRANSACTION-ASSISTANT-073 - Tiền phạt: Chi tiết có liên kết người gửi hợp lệ";
    public static final String TRANSACTION_ASSISTANT_074 = "TRANSACTION-ASSISTANT-074 - Tiền phạt: URL chi tiết có đúng một ID và giữ loại giao dịch";
    public static final String TRANSACTION_ASSISTANT_075 = "TRANSACTION-ASSISTANT-075 - Tiền phạt: Refresh giữ nguyên chi tiết đang mở";
    public static final String TRANSACTION_ASSISTANT_076 = "TRANSACTION-ASSISTANT-076 - Tiền phạt: Deep link mở lại đúng chi tiết giao dịch";
    public static final String TRANSACTION_ASSISTANT_077 = "TRANSACTION-ASSISTANT-077 - Tiền phạt: Back và Forward đóng rồi mở lại chi tiết";
    public static final String TRANSACTION_ASSISTANT_082 = "TRANSACTION-ASSISTANT-082 - Tiền phạt: Mở dòng khác cập nhật URL và nội dung chi tiết";
    public static final String TRANSACTION_ASSISTANT_083 = "TRANSACTION-ASSISTANT-083 - Tiền phạt: Liên kết dòng tiền mở đúng giao dịch liên quan";
    public static final String TRANSACTION_ASSISTANT_084 = "TRANSACTION-ASSISTANT-084 - Tiền phạt: Icon đóng loại bỏ ID và giữ route hiện tại";
    public static final String TRANSACTION_ASSISTANT_085 = "TRANSACTION-ASSISTANT-085 - Tiền phạt: Xuất Excel cho loại giao dịch đang chọn";
    public static final String TRANSACTION_ASSISTANT_086 = "TRANSACTION-ASSISTANT-086 - Tiền phạt: Xuất Excel sau khi lọc trạng thái";
    // Các ID 070-072, 078-081 đã hợp nhất và không được tái sử dụng.
    public static final String TRANSACTION_ASSISTANT_087 = "TRANSACTION-ASSISTANT-087 - Tiền phạt: Chi tiết khớp trạng thái, số tiền và thời gian dòng đã chọn";
    public static final String TRANSACTION_ASSISTANT_088 = "TRANSACTION-ASSISTANT-088 - Tiền phạt: Lịch sử dòng tiền tải xong và hiển thị đầy đủ số tổng";
    public static final String TRANSACTION_ASSISTANT_089 = "TRANSACTION-ASSISTANT-089 - Tiền phạt: Giao dịch đang xem tải được và khớp dữ liệu nguồn";

    public static final String TRANSACTION_SYSTEM_001 = "TRANSACTION-SYSTEM-001 - Hệ thống: Hiển thị đầy đủ các loại giao dịch con";
    public static final String TRANSACTION_SYSTEM_002 = "TRANSACTION-SYSTEM-002 - Hệ thống: Mở đúng route và đánh dấu loại đang chọn";
    public static final String TRANSACTION_SYSTEM_003 = "TRANSACTION-SYSTEM-003 - Hệ thống: Hiển thị đúng bộ lọc và cột dữ liệu";
    public static final String TRANSACTION_SYSTEM_004 = "TRANSACTION-SYSTEM-004 - Hệ thống: Dòng giao dịch có định dạng hợp lệ";
    public static final String TRANSACTION_SYSTEM_005 = "TRANSACTION-SYSTEM-005 - Hệ thống: Tìm kiếm người dùng và Reset khôi phục dữ liệu";
    public static final String TRANSACTION_SYSTEM_006 = "TRANSACTION-SYSTEM-006 - Hệ thống: Bộ lọc hiển thị lựa chọn và giữ đúng tab";
    public static final String TRANSACTION_SYSTEM_007 = "TRANSACTION-SYSTEM-007 - Hệ thống: Sắp xếp số tiền tăng và giảm dần";
    public static final String TRANSACTION_SYSTEM_008 = "TRANSACTION-SYSTEM-008 - Hệ thống: Mở và đóng chi tiết giao dịch";
    public static final String TRANSACTION_SYSTEM_009 = "TRANSACTION-SYSTEM-009 - Hệ thống: Phân trang và Reset giữ đúng tab";
    public static final String TRANSACTION_SYSTEM_010 = "TRANSACTION-SYSTEM-010 - Hệ thống: Xuất Excel cho loại giao dịch đang chọn";

    private TransactionHistoryTestCases() {
    }
}
